services:
  api:
    build: ./
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    user: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - 8080:8080
